### ISSUE TITLE
Restoring Archived Client does not remove Address from Address Group

### ISSUE THREAD

**Issue by UBNT-Jordan** [U-CRM/billing#126]
When a client is archived the Service IP is added to the Blocked_Users address group properly, but when the client is restored and no longer in Archive state, the Service IP remains in the address group.

**Comment by keksa** [comment]
Thank you for the report, we'll take a look.

**Comment by UBNT-Petr** [comment]
Hi Jordan, this is the standard behavior. When a client is restored, related services remain "Ended". Thus it is correct to block the IPs. And this is how it should work because when you restore a client you don't want to activate his old services automatically, you will probably create a new service for him.

In upcoming version 2.2.3-beta1 we will introduce a feature to simply reactivate an ended service. So the process will be even easier.
